# Generated by Django 3.2.9 on 2021-11-17 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Mpaa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
                ('ban', models.BooleanField()),
                ('can_post_texts', models.BooleanField()),
                ('publicName', models.CharField(max_length=128)),
                ('contact', models.CharField(max_length=256, null=True)),
                ('about', models.CharField(max_length=512, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Texts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(max_length=300)),
                ('notes', models.TextField(max_length=300)),
                ('text', models.TextField()),
                ('likes', models.IntegerField()),
                ('dislikes', models.IntegerField()),
                ('timeOfCreate', models.DateTimeField(auto_now_add=True)),
                ('timeOfUpadate', models.DateTimeField(auto_now_add=True)),
                ('mpaa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='TiF.mpaa')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text', to='TiF.users')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text', to='TiF.choices')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcat', to='TiF.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt', models.TextField(max_length=1000)),
                ('timeOfCreate', models.DateTimeField(auto_now_add=True)),
                ('timeOfUpadate', models.DateTimeField(auto_now_add=True)),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Mess', to='TiF.users')),
                ('message_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='TiF.users')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(max_length=300)),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='TiF.users')),
                ('text_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='TiF.texts')),
            ],
        ),
    ]
