# Generated by Django 3.2.9 on 2021-11-17 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TiF', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Categorie',
        ),
        migrations.RenameModel(
            old_name='Choices',
            new_name='Choice',
        ),
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
        migrations.RenameModel(
            old_name='Messages',
            new_name='Message',
        ),
        migrations.RenameModel(
            old_name='Texts',
            new_name='Text',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
