# Generated by Django 3.2.9 on 2021-11-18 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TiF', '0003_auto_20211118_0015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='textdep',
            old_name='found_id',
            new_name='found',
        ),
        migrations.RenameField(
            model_name='textdep',
            old_name='text_id',
            new_name='text',
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=100)),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='TiF.text')),
            ],
        ),
    ]
