# Generated by Django 3.2.9 on 2021-11-18 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TiF', '0004_auto_20211118_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagname', to='TiF.text'),
        ),
        migrations.AlterField(
            model_name='text',
            name='mpaa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mpaa', to='TiF.mpaa'),
        ),
        migrations.AlterField(
            model_name='text',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='TiF.user'),
        ),
        migrations.AlterField(
            model_name='text',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='TiF.choice'),
        ),
        migrations.AlterField(
            model_name='textdep',
            name='found',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_deps', to='TiF.foundation'),
        ),
        migrations.AlterField(
            model_name='textdep',
            name='text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_deps', to='TiF.text'),
        ),
    ]
